<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivia Varricchione">
<meta name="dcterms.date" content="2024-03-02">

<title>Data Visualization Blog - Blog Post 3: Chocolate Rating</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Data Visualization Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Blog Post 3: Chocolate Rating</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Olivia Varricchione </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 2, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Introduction</p>
<p>This analysis will be using the chocolate data set from tidyTuesday: https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-01-18/readme.md which has 2530 observations. The variables of interest include rating, cocoa percent, country of bean origin, and company location. More specifically, the country of bean origin and company location were used to create variables for the continent of bean origin and continent of company location to decrease the different levels of those variables. This analysis will focus on predicting the chocolate rating based on the cocoa percent, the continent of bean origin, and the company continent.</p>
<p>Primary Visualizations</p>
<p>To start, the data was wrangled to change the country of bean origin and the company country to be in the form of a continent so it would be a predictor that is much easier to visualize since it has less levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>chocolate <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2530 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): company_manufacturer, company_location, country_of_bean_origin, spe...
dbl (3): ref, review_date, rating

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>chocolate_data <span class="ot">&lt;-</span> chocolate <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rating, cocoa_percent, country_of_bean_origin, company_location) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(cocoa_percent, <span class="at">into =</span> <span class="st">"cocoa_percent"</span>, <span class="at">sep =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cocoa_percent =</span> <span class="fu">as.numeric</span>(cocoa_percent)) <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">company_continent =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    company_location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Canada"</span>, <span class="st">"Costa Rica"</span>, <span class="st">"Dominican Republic"</span>, <span class="st">"El Salvador"</span>, <span class="st">"Grenada"</span>, <span class="st">"Guatemala"</span>, <span class="st">"Honduras"</span>, <span class="st">"Martinique"</span>, <span class="st">"Mexico"</span>, <span class="st">"Nicaragua"</span>, <span class="st">"Puerto Rico"</span>, <span class="st">"St. Lucia"</span>, <span class="st">"St. Vincent-Grenadines"</span>, <span class="st">"U.S.A."</span>) <span class="sc">~</span><span class="st">"North America"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    company_location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Argentina"</span>, <span class="st">"Bolivia"</span>, <span class="st">"Brazil"</span>, <span class="st">"Chile"</span>, <span class="st">"Colombia"</span>, <span class="st">"Ecuador"</span>, <span class="st">"Peru"</span>, <span class="st">"Suriname"</span>, <span class="st">"Venezuela"</span>) <span class="sc">~</span><span class="st">"South America"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    company_location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Amsterdam"</span>, <span class="st">"Austria"</span>, <span class="st">"Belgium"</span>, <span class="st">"Czech Republic"</span>, <span class="st">"Denmark"</span>, <span class="st">"Finland"</span>, <span class="st">"France"</span>, <span class="st">"Germany"</span>, <span class="st">"Hungary"</span>, <span class="st">"Iceland"</span>, <span class="st">"Ireland"</span>, <span class="st">"Italy"</span>, <span class="st">"Lithuania"</span>, <span class="st">"Netherlands"</span>, <span class="st">"Norway"</span>, <span class="st">"Poland"</span>, <span class="st">"Portugal"</span>, <span class="st">"Russia"</span>, <span class="st">"Scotland"</span>, <span class="st">"Spain"</span>, <span class="st">"Sweden"</span>, <span class="st">"Switzerland"</span>, <span class="st">"U.K."</span>, <span class="st">"Wales"</span>) <span class="sc">~</span><span class="st">"Europe"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    company_location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Ghana"</span>, <span class="st">"Madagascar"</span>, <span class="st">"Sao Tome"</span>, <span class="st">"Sao Tome &amp; Principe"</span>, <span class="st">"South Africa"</span>) <span class="sc">~</span><span class="st">"Africa"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    company_location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"India"</span>, <span class="st">"Israel"</span>, <span class="st">"Japan"</span>, <span class="st">"Malaysia"</span>, <span class="st">"Philippines"</span>, <span class="st">"Singapore"</span>, <span class="st">"South Korea"</span>, <span class="st">"Taiwan"</span>, <span class="st">"Thailand"</span>, <span class="st">"U.A.E."</span>, <span class="st">"Vietnam"</span>) <span class="sc">~</span><span class="st">"Asia"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    company_location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Australia"</span>, <span class="st">"Fiji"</span>, <span class="st">"New Zealand"</span>, <span class="st">"Vanuatu"</span>) <span class="sc">~</span><span class="st">"Oceania"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bean_continent =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    country_of_bean_origin <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Belize"</span>,<span class="st">"Costa Rica"</span>, <span class="st">"Cuba"</span>, <span class="st">"Dominican Republic"</span>, <span class="st">"El Salvador"</span>, <span class="st">"Grenada"</span>, <span class="st">"Guatemala"</span>, <span class="st">"Haiti"</span>, <span class="st">"Honduras"</span>, <span class="st">"Jamaica"</span>, <span class="st">"Martinique"</span>, <span class="st">"Mexico"</span>, <span class="st">"Nicaragua"</span>, <span class="st">"Panama"</span>, <span class="st">"Puerto Rico"</span>, <span class="st">"St. Lucia"</span>, <span class="st">"St. Vincent-Grenadines"</span>, <span class="st">"U.S.A."</span>) <span class="sc">~</span> <span class="st">"North America"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    country_of_bean_origin <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Bolivia"</span>, <span class="st">"Brazil"</span>, <span class="st">"Colombia"</span>, <span class="st">"Ecuador"</span>, <span class="st">"Peru"</span>, <span class="st">"Suriname"</span>, <span class="st">"Tobago"</span>, <span class="st">"Trinidad"</span>, <span class="st">"Venezuela"</span>) <span class="sc">~</span> <span class="st">"South America"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    country_of_bean_origin <span class="sc">%in%</span> <span class="fu">c</span>() <span class="sc">~</span> <span class="st">"Europe"</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    country_of_bean_origin <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Cameroon"</span>, <span class="st">"Congo"</span>, <span class="st">"DR Congo"</span>, <span class="st">"Gabon"</span>, <span class="st">"Ghana"</span>, <span class="st">"Ivory Coast"</span>, <span class="st">"Liberia"</span>, <span class="st">"Madagascar"</span>, <span class="st">"Nigeria"</span>, <span class="st">"Principe"</span>, <span class="st">"Sao Tome"</span>, <span class="st">"Sao Tome &amp; Principe"</span>, <span class="st">"Sierra Leone"</span>, <span class="st">"Tanzania"</span>, <span class="st">"Togo"</span>, <span class="st">"Uganda"</span>) <span class="sc">~</span> <span class="st">"Africa"</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    country_of_bean_origin <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Burma"</span>, <span class="st">"China"</span>, <span class="st">"India"</span>, <span class="st">"Indonesia"</span>, <span class="st">"Malaysia"</span>, <span class="st">"Philippines"</span>, <span class="st">"Sri Lanka"</span>, <span class="st">"Sulawesi"</span>, <span class="st">"Sumatra"</span>, <span class="st">"Taiwan"</span>, <span class="st">"Thailand"</span>, <span class="st">"Vietnam"</span>) <span class="sc">~</span> <span class="st">"Asia"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    country_of_bean_origin <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Australia"</span>, <span class="st">"Fiji"</span>, <span class="st">"Papua New Guinea"</span>, <span class="st">"Samoa"</span>, <span class="st">"Solomon Islands"</span>, <span class="st">"Vanuatu"</span>) <span class="sc">~</span> <span class="st">"Oceania"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bean_continent =</span> <span class="fu">as.factor</span>(bean_continent)) <span class="sc">|&gt;</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">company_continent =</span> <span class="fu">as.factor</span>(company_continent)) <span class="sc">|&gt;</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A linear model was then created to predict the chocolate rating based on the cocoa percent, continent of bean origin, and the company continent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> cocoa_percent <span class="sc">+</span> bean_continent <span class="sc">+</span> company_continent, <span class="at">data =</span> chocolate_data)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 5
   term                           estimate std.error statistic   p.value
   &lt;chr&gt;                             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)                     3.82      0.145      26.3   3.34e-134
 2 cocoa_percent                  -0.0112    0.00166    -6.74  1.96e- 11
 3 bean_continentAsia             -0.0133    0.0410     -0.324 7.46e-  1
 4 bean_continentNorth America    -0.00890   0.0277     -0.322 7.48e-  1
 5 bean_continentOceania          -0.0189    0.0531     -0.357 7.21e-  1
 6 bean_continentSouth America     0.00518   0.0271      0.191 8.49e-  1
 7 company_continentAsia           0.167     0.0953      1.75  8.04e-  2
 8 company_continentEurope         0.211     0.0866      2.44  1.50e-  2
 9 company_continentNorth America  0.186     0.0860      2.16  3.06e-  2
10 company_continentOceania        0.272     0.0996      2.73  6.43e-  3
11 company_continentSouth America  0.107     0.0925      1.16  2.46e-  1</code></pre>
</div>
</div>
<p>We can see that for every increase in the cocoa percentage, the predicted rating is expected to decrease by 0.0112 assuming the continent of bean origin and company continent remains the same. Similarly, we see that for a bean origin of Asia, North America, and Oceania the predicted rating is expected to be less than the reference (Africa) assuming the cocoa percentage and company continent remains the same. However, for a South America bean origin, the predicted rating is expected to be 0.00518 higher than Africa for the same cocoa_percent and company continent. Finally, we see that for a company continent of Asia, Europe, North America, Oceania, or Sourth America the predicted rating is expected to be higher than the reference (Africa) if the cocoa percentage and bean origin remain constant. For example, for a European company, the rating is predicted to be 0.211 higher than an African company for the same cocoa percentage and the same bean origin continent. All of these observations would be easier to see in a visualization. So, let’s visualize this data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'modelr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:broom':

    bootstrap</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> chocolate_data <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data_grid</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cocoa_percent =</span> <span class="fu">seq_range</span>(cocoa_percent, <span class="at">n =</span> <span class="dv">6</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">company_continent =</span> chocolate_data <span class="sc">|&gt;</span> <span class="fu">pull</span>(company_continent) <span class="sc">|&gt;</span> <span class="fu">levels</span>(),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">bean_continent =</span> chocolate_data <span class="sc">|&gt;</span> <span class="fu">pull</span>(bean_continent) <span class="sc">|&gt;</span> <span class="fu">levels</span>()</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>grid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 180 × 3
   cocoa_percent company_continent bean_continent
           &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;         
 1            42 Africa            Africa        
 2            42 Africa            Asia          
 3            42 Africa            North America 
 4            42 Africa            Oceania       
 5            42 Africa            South America 
 6            42 Asia              Africa        
 7            42 Asia              Asia          
 8            42 Asia              North America 
 9            42 Asia              Oceania       
10            42 Asia              South America 
# ℹ 170 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(model, <span class="at">newdata =</span> grid, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>aug</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 180 × 6
   cocoa_percent company_continent bean_continent .fitted .lower .upper
           &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1            42 Africa            Africa            3.35   3.16   3.54
 2            42 Africa            Asia              3.34   3.13   3.54
 3            42 Africa            North America     3.34   3.15   3.54
 4            42 Africa            Oceania           3.33   3.12   3.55
 5            42 Africa            South America     3.36   3.16   3.56
 6            42 Asia              Africa            3.52   3.39   3.65
 7            42 Asia              Asia              3.51   3.38   3.63
 8            42 Asia              North America     3.51   3.38   3.64
 9            42 Asia              Oceania           3.50   3.34   3.66
10            42 Asia              South America     3.52   3.40   3.65
# ℹ 170 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> chocolate_data, <span class="fu">aes</span>(<span class="at">x =</span> cocoa_percent, <span class="at">y =</span> rating)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> aug, <span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">colour =</span> company_continent)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>bean_continent) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Predicted Rating"</span>, <span class="at">x =</span> <span class="st">"Cocoa Percent"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this visualization, we can see that for all of the company continents, the predicted rating decreases for higher cocoa percents. We can also see that African companies seem to have a lower predicted rating whereas Oceania companies seem to have a higher rating. However, we can also see that this might not be the best model as the relationship, meaning the slope, between cocoa percent and rating does not change depending on the company continent. We can fix this by incorporating an interaction between variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> cocoa_percent <span class="sc">+</span> bean_continent <span class="sc">+</span> cocoa_percent<span class="sc">:</span>bean_continent <span class="sc">+</span> company_continent, <span class="at">data =</span> chocolate_data)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="sc">|&gt;</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 5
   term                                    estimate std.error statistic  p.value
   &lt;chr&gt;                                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)                              3.96e+0   0.349     11.4    3.98e-29
 2 cocoa_percent                           -1.31e-2   0.00471   -2.78   5.55e- 3
 3 bean_continentAsia                      -3.48e-1   0.652     -0.534  5.94e- 1
 4 bean_continentNorth America             -3.15e-1   0.410     -0.769  4.42e- 1
 5 bean_continentOceania                   -7.31e-1   0.645     -1.13   2.57e- 1
 6 bean_continentSouth America             -9.78e-3   0.375     -0.0261 9.79e- 1
 7 company_continentAsia                    1.67e-1   0.0954     1.75   8.09e- 2
 8 company_continentEurope                  2.11e-1   0.0867     2.43   1.52e- 2
 9 company_continentNorth America           1.85e-1   0.0861     2.15   3.16e- 2
10 company_continentOceania                 2.66e-1   0.0998     2.66   7.81e- 3
11 company_continentSouth America           1.04e-1   0.0926     1.13   2.60e- 1
12 cocoa_percent:bean_continentAsia         4.68e-3   0.00911    0.514  6.07e- 1
13 cocoa_percent:bean_continentNorth Amer…  4.29e-3   0.00573    0.749  4.54e- 1
14 cocoa_percent:bean_continentOceania      9.99e-3   0.00902    1.11   2.68e- 1
15 cocoa_percent:bean_continentSouth Amer…  2.25e-4   0.00524    0.0430 9.66e- 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>aug2 <span class="ot">&lt;-</span> <span class="fu">augment</span>(model2, <span class="at">newdata =</span> grid, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>aug2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 180 × 6
   cocoa_percent company_continent bean_continent .fitted .lower .upper
           &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1            42 Africa            Africa            3.41   3.09   3.73
 2            42 Africa            Asia              3.26   2.77   3.74
 3            42 Africa            North America     3.27   3.02   3.53
 4            42 Africa            Oceania           3.10   2.62   3.58
 5            42 Africa            South America     3.41   3.19   3.63
 6            42 Asia              Africa            3.58   3.29   3.86
 7            42 Asia              Asia              3.43   2.97   3.88
 8            42 Asia              North America     3.44   3.23   3.65
 9            42 Asia              Oceania           3.27   2.81   3.72
10            42 Asia              South America     3.58   3.42   3.74
# ℹ 170 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> chocolate_data, <span class="fu">aes</span>(<span class="at">x =</span> cocoa_percent, <span class="at">y =</span> rating)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> aug2, <span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">colour =</span> company_continent)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>bean_continent) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Predicted Rating"</span>, <span class="at">x =</span> <span class="st">"Cocoa Percent"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this visualization we can see that if the bean continent is Africa or South America, there is a steeper slope in the decrease in rating as the cocoa percent increases, whereas Oceania does not have too much of a decrease with an increase in cocoa percentage.</p>
<p>Conclusion and Wrap-Up</p>
<p>From this analysis found that the as the cocoa percentage increased, the predicted rating decreased, with African companies having lower ratings and Oceania companies having higher ratings. Additionally, there was a steeper decrease for African and South American bean origins and a more level trend for Oceania bean origins. In the future, it would be interesting to see the trend of individual countries within the continents, as this is the data that was originally provided and it would allow us to see more specifically which countries have the best retention of rating with an increase in cocoa percentage.</p>
<p>Connection to Class Ideas</p>
<p>These visualizations relate to class because of the use of linear models. We have spent a lot of time in class using the model, grid, augment, visualize method to create data visualizations for models. These visualizations makes it easier to see the trends in predicted values, especially if the target audience is someone without a statistical background.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>